version: '2.2'

services:
  flask-gpt:
    image: edgecrush3r/flask-gpt:latest
    network_mode: bridge
    build:
      context: .
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=""
      - OPENAI_ORGANIZATION=""      